---
title: "BI586_dada2_analysis"
author: "Elsa Brenner, Jamie Poirier, Erica Sun"
date: "March 9, 2021"
output: html_document
---
# this is our shared R Markdown Document =) 

VERSION CONTROL: 
R- 4.0.4
dada2- 1.16.0
ggplot2- 3.3.3
ShortRead- 1.48.0
phyloseq- 1.34.0

INTRODUCTION: 



METHODS AND DATA ANALYSIS: 

CONCLUSION: 

---
# Downloading .fastq files from NCBI SRA
First, we have to download our data from [NCBI BioSample](https://www.ncbi.nlm.nih.gov/biosample?LinkName=bioproject_biosample_all&from_uid=628692). We chose 5 offshore and 5 inshore samples of *Siderastrea siderea* for our analysis. Now we can download all the sample number (starting with SRR) directly on NCBI by using the "send to" feature with settings:
Format = "Accessions List" and
Sort By = "Default order". 
Then save the accessions list with file name srafile.

Now we are ready to download our sequences.
```{css,echo=F}
.sccCode {
  background-color: black;
  color: white;}
```

```{bash, eval = F, echo = T, class.source="sccCode"}
$ prefetch --option-file srafile
```
We just downloaded all the sample runs as .sra files! Now we have to convert them into .fastq
```{bash, eval = F, echo = T, class.source="sccCode"}
# First let's make a directory to store our output .fastq files
$ mkdir sraout
# Convert them to .fastq and store the output in the sraout director
$ fastq-dump --split-files ./SRR* -O sraout/
```
That's it! Now we have all of our sampels in .fastq format.

REFERENCES: 
